spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/barbearia_db
    username: {username}
    password: {password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: brb

logging:
  level:
    org.springframework.security: DEBUG
